spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789013

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

jwt:
  secret: 12345678901234567890123456789012